jaroslawhartman/withings-sync

setup.py
withings_sync/garmin.py

Garmin Connect is behind Cloudflare nowadays.  This means that direct use of the requests library is not sufficient anymore to post data. 
The cloudscraper library takes care of this for us.

Fix Garmin SSO Authentication error

---

contrib/k8s-deploy.yaml

The contrib/ directory already has an example of using a kubernetes job to run the sync.  I've re-written it as a deployment and fixed a few minor issues (e.g. permitting to run as root by default, fully qualified container name, etc) along the way.

Create sample kubernetes deployment

---

withings_sync/withings2.py

The new endpoint needs an additional parameter 'action' to work properly.

Fix new endpoint parameters

---

setup.py
withings_sync/garmin.py

I fixed the CloudFlare 403 error by using HTTP/2. I replaced the cloudscraper library in garmin.py. This fix might work as well for the 401 error, but I could not test this as I only had 403 errors.

Fix for the Cloudflare 403 error with http2 and the Garmin username is being parsed correctly again.

---

README.md

Since the pull limit is in place and we're now going to deploy to ghcr.io, use this repository.

remove link to docker hub

---

README.md
withings_sync/sync.py

_This is an update of #42_
For backup purpose and to upload body measurements to platforms other than Garmin and TrainerRoad I would like to store the FIT or JSON data in a file. Because the original --no-upload mixes log messages and FIT or JSON data on stdout it is not possible to just redirect the output to a file. This patch adds --output to the list of arguments to specify a base filename where the FIT or JSON data is stored.
Attention: This patch changes the previous behavior of --no-upload which now doesn't print the FIT or JSON data to stdout.

Add possibility to save downloaded FIT data to file (reworked)

---

README.md
withings_sync/sync.py

Hi, I'm using your code in [Rancher](https://rancher.com), and made the modification in this PR to grab the credentials from Rancher secrets rather than environment variables or directly. I thought you might find it useful to merge, though no offence if you don't want the cruft.
n.b. it looks as though the `contrib/k8s*` files now in the repo achieve the same goal for k8s for the st0vg container image. It would be better not to have to build my own image as I do now, but I don't think the k8s config works for Rancher.
The secrets files are:
- `/run/secrets/garmin_username` — Garmin Connect username
- `/run/secrets/garmin_password` — Garmin Connect password
- `/run/secrets/trainerroad_username` — TrainerRoad username
- `/run/secrets/trainerroad_password` — TrainerRoad password

Attempt to set credentials from secrets files

---

withings_sync/sync.py
withings_sync/withings2.py

This patch should address issues of the same data being uploaded to Garmin if the sync is run multiple times per day as mentioned in issue #23 
It stores the timestamp of the last time the sync was run in the Withings user config file if no `--fromdate/-f` is provided on the command line.  
I've only done light testing, there might be edge cases not accounted for in the code.  
I'm not sure how Garmin/Withings deals with timezones, so there might need to be timezone shenanigan added as well.

Multiple uploads of the same data

---

withings_sync/sync.py

Good afternoon, 
This PR is a first attempt to add some Python Code Style to the code with checks vs black & pylint.  
Rationale: my editor tends to complain about this on every save.  
For now, it's only done for one file (sync.py) and not fully completed yet (see pylint output below) I am wondering what your opinions are about this.  
Fixing the remaining 3 recommendations require some code restructuring, I'll leave that for a follow-up PR. 
```
Module withings_sync.sync
sync.py:134:0: R0914: Too many local variables (26/15) (too-many-locals)
sync.py:134:0: R0912: Too many branches (26/12) (too-many-branches)
sync.py:134:0: R0915: Too many statements (93/50) (too-many-statements)
------------------------------------------------------------------
Your code has been rated at 9.81/10 …
```

Python Code Style changes (black & pylint) for sync.py

---

withings_sync/sync.py

Gives more details on what is going on in cases such as https://github.com/jaroslawhartman/withings-sync/issues/44

sync.py: add python version check / requires python3

---

withings_sync/sync.py

With merging of PR #39 a mismatch between checked and read environment variables had been introduced to master and broke reading of Garmin and Trainerroad credentials from environment. This change uses the right variables in checking.

Fix mismatch in checking and retrieving environment

---

Dockerfile

request has a fix dependency on charset-normalizer charset_normalizer~=2.0.0 (see https://requests.readthedocs.io/en/latest/user/advanced/#encodings)
Is this the way this issue should be resolved? I'm happy about every comment or suggestion.

fix Dockerfile: downgrade charset-normalizer

---

contrib/k8s-job.yaml

The minute field in the current K8s cron example is `*`, which means that it will run every minute (0-60) of every qualifying third hour (`*/3`).
Based on the documentation, I don't think that's the intention.

Fix K8s cron example to not run every minute

---

.gitignore
setup.py
withings_sync/sync.py

During sync error when dealing with #80 I noticed that last sync info gets stored even if no data were uploaded/synchronized. I changed the order of call to store last sync only if no exception/error occurred before.

Store lastsync info only if no error occurred

---

withings_sync/sync.py

It seems that by commenting out, there is an issue because the map entry is empty. 
With this fix, we delete the entry if no weight is in the list. This is untested. I assume that this is the cause for #100, #98 and #86

fix: enable skip if row doesn't contain weight

---

withings_sync/sync.py

When reading from docker secrets, the usename and password must be stripped of trailing whitespace. This will possibly fix many of the 401-errors people are seeing.  (At least that was the problem here).

Strip whitespace from docker-secrets

---

withings_sync/sync.py

See #111 : bump python minimum required version from 3.0 to 3.7

bump python minimum required version from 3.0 to 3.7

---

withings_sync/trainerroad.py

Hi, I found a fix for #83 
It seems that TrainerRoad is requiring this additional key-value pair to be present in the POST request

Fix trainerroad sync problem

---

withings_sync/sync.py

Apology in advance, my English might not make sense at all, or my understanding of codebase is totally off.
This will hopefully fix the incorrect date/time in log output.
Let's say that `last_sync` in `.withings_user.json` is as follows:
```
"last_sync": 1680243105,
```
which is equal to "2023/3/31 15:11:45" in JST(UTC+9), and matches the timezone of my pc.
When there is nothing to sync, log output should look like this:
```
2023-03-31 15:26:10,748 - withings - INFO - Refresh Access Token
2023-03-31 15:26:11,913 - root - INFO - Fetching measurements from 2023-03-31 15:11 to 2023-03-31 23:59
2023-03-31 15:26:12,890 - withings - INFO - Get Measurements
2023-03-31 15:26:13,850 - root - ERROR - No measurements to upload for date or period specified
```
On the 2nd line, it says that …

Fix the incorrect date/time log output generated by sync.py

---

.github/workflows/build-publish.yml

gh-action-pypi-publish: The master branch version has been sunset. Please, change the GitHub Action version you use from master to release/v1 or use an exact tag, or a full Git commit SHA.
I found this message, when investigation why the build failed:
> You are using "pypa/gh-action-pypi-publish@master". The "master" branch of this project has been sunset and will not receive any updates, not even security bug fixes. Please, make sure to use a supported version. If you want to pin to v1 major version, use "pypa/gh-action-pypi-publish@release/v1". If you feel adventurous, you may opt to use use "pypa/gh-action-pypi-publish@unstable/v1" instead. A more general recommendation is to pin to exact tags or commit shas.
This PR switches to the release version v1 as supposed in [their …

chore: change pypa gh action publish to release

---

setup.py

As mentioned in https://github.com/jaroslawhartman/withings-sync/issues/123, replace the url to the repository, so that pypi shows the correct link.

Add url to this github repo

---

requirements.txt
setup.py
withings_sync/garmin.py

Garmin no longer support auth via the former authentication flow. The Garth library implements authentication via OAuth, which is the recommended methods.
I implemented a solution for this problem in related Python repositories:
- https://github.com/pe-st/garmin-connect-export/pull/96
- https://github.com/petergardfjall/garminexport/pull/104
For this particular one: I'm personally not a Withings user, so I couldn't end-to-end test the solution. Please test before merging.
For full context, see the relevant issue thread: https://github.com/pe-st/garmin-connect-export/issues/95
```
Garmin shut down the old authentication flow. The new authentication flow has many security measures in place to script the login. We can use the Garth library to implement an OAuth flow, which should be more …
```

Migrate Garmin authentication to Garth OAuth fixes #128

---

withings_sync/sync.py

Last sync value was always updated, even after an unsuccessful sync.  This should prevent this.

sync.py: update last_sync value after successful sync

---

requirements.txt
setup.py
withings_sync/garmin.py
withings_sync/sync.py

To reduce the requests during garmin login, the garth session information is stored similar to the withing session data. Also garth is used to upload the fit-file and cloudscrapper is no longer required. I don't know if we can get rid of cloudscrapper or if there is still an advantage if the upload is done with cloudscrapper.
As with my other PR: If you like these changes let me know and I can cleanup. For example the directory in which the garth session is stored should be defined at a central place.

Store the garth session information and upload the fit file via garth

---

setup.py

Lack of version change will result in wrong version reporting in debug logging.
I propose a quick release to go from 4.2.0 to 4.2.1 just to fix this.

Update release version

---

withings_sync/sync.py

Error accessing variable 'gar_wg_state' when only using Withings blood pressure device.  Moved set_lastsyn() under reach fit_data if statements so the other variable isn't used..
UnboundLocalError: cannot access local variable 'gar_wg_state' where it is not associated with a value

Add gar_wg_state and gar_bp_state variables to Sync.py

---

contrib/k8s-deployment.yaml
contrib/k8s-job.yaml

fix: set apiVersion of chronjob to `batch/v1` as `batch/v1beta1` is deprecated (check https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)

fix: use correct image in k8s-deployment.yaml

---

withings_sync/sync.py

solves #161 where a misleading error message was printed.

#161: Errors message not correct when garmin username is set, but no data should be synced

---

withings_sync/garmin.py

Just a quick update to `garmin.py` to use `os.path.join()`, isort, black and some pythonic constructs. Still working my way through some of the issues around creation of duplicate entries when using `--fromdate` via the API.

Refactoring cleanup, pythonic updates, black formatting
